### PR TITLE
random number generator

### PR DESCRIPTION
**Pull request by onners-dev**
adding random number generator, in addition to the alphabets!

### CODE REVIEW

**Review by weirdsir — APPROVED** [review]
amazing thank you

**Review by dkrpv — CHANGES_REQUESTED** [review]
Capitalise the letters

**Review by weirdsir — CHANGES_REQUESTED** [review]
More numbers?

**Review by weirdsir — APPROVED** [review]
Good, you're not getting fired :)

**Review by dkrpv — APPROVED** [review]
Will discuss during scrum. Issue resolved

**Pull request merged**
