### PR TITLE
Add color iteration

### PR DESCRIPTION
**Pull request by dkrpv**
Every letter of the alphabet now different color

### CODE REVIEW

**Review by weirdsir — APPROVED** [review]
Nice

**Review by onners-dev — APPROVED** [review]
very nice code, maybe add a user interface

**Review by onners-dev — CHANGES_REQUESTED** [review]
please add a user interface!!!!

**Review by weirdsir — APPROVED** [review]
Very fancy

**Review by onners-dev — APPROVED** [review]
nerd

**Pull request merged**
